import os
import numpy as np
import platform
import yaml

root_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sota_root = os.path.join(root_dir, "sota", "Titanic")
ROOT_DIR = os.getenv("LLMGE_ROOT_DIR", root_dir)
SLURM_CONFIG_DIR = os.getenv(
    "LLMGE_SLURM_CONFIG_DIR",
    os.path.join(ROOT_DIR, "slurm-config"),
)
CLUSTER = os.getenv("LLMGE_CLUSTER", "pace-ice")
DATA_PATH = os.path.join(ROOT_DIR, "sota/titanic/data")
SOTA_ROOT = os.getenv("LLMGE_SOTA_ROOT", sota_root)
SEED_NETWORK = os.getenv(
    "LLMGE_SEED_NETWORK",
    os.path.join(SOTA_ROOT, "model.py"),
)
MODEL = "model"
# Path to local LLM model path used by server.py for LLM operations
HF_HOME = os.getenv("HF_HOME", "/storage/ice-shared/vip-vvk/llm_storage/")
MODEL_PATH = "/storage/ice-shared/vip-vvk/llm_storage/meta-llama/Llama-3.3-70B-Instruct/"
VARIANT_DIR = os.path.join(SOTA_ROOT, "models/llmge_models") 
TRAIN_FILE = os.path.join(SOTA_ROOT, "eval.py") 
ISLAND_TEMP_SCRIPT = os.path.join("src", "island_temp_script_{ISLAND_NUM}.sh")

# Where Slurm job outputs are written (matches sbatch --output paths)
SLURM_OUTPUT_PATH = "run_job_outputs/"

# Where the vLLM server writes per-request latency/token metrics.
RUN_METRICS_DIR = os.path.join(ROOT_DIR, "run_metrics")

# Prompt templates glob relative to the repository root
DEFAULT_PROMPT_GROUP = "FixedPrompts"
PROMPTS = f"templates/{DEFAULT_PROMPT_GROUP}/**/*.txt"

# TODO: Adding this here, I think it's supposed to parse from the command line
OUTPUT_DIR = "titanic_test"
PORT = int(os.getenv("LLMGE_PORT", "22414"))

LLM_MODEL = 'llama3.3'
PACE_ICE = True

# Available LLM identifiers
LLM_QWEN = 'qwen25'
LLM_MIXTRAL = 'mixtral'
LLM_LLAMA3 = 'llama3'
LLM_GEMMA2 = 'gemma2'
LLM_GEMMA3 = 'gemma3'
LLM_DEEPSEEK = 'deepseek'
LLM_GEMINI = 'gemini'

USE_VLLM = os.getenv("LLMGE_USE_VLLM", "1").lower() in ("1", "true", "yes")
USE_LOAD_BALANCING = os.getenv("LLMGE_USE_LOAD_BALANCING", "0").lower() in ("1", "true", "yes")

# Load balancing configuration
SERVER_REGISTRY_FILE = os.getenv("SERVER_REGISTRY_FILE", os.path.join(ROOT_DIR, "servers.json"))
LOAD_BALANCER_PORT = int(os.getenv("LOAD_BALANCER_PORT", "9000"))
LOADBALANCER_LOG_FILE = os.getenv("LOADBALANCER_LOG_FILE", os.path.join(ROOT_DIR, "loadbalancer.log"))

# LLMs allowed for island runs
ISLAND_LLMS = [LLM_QWEN, LLM_MIXTRAL, LLM_DEEPSEEK, LLM_LLAMA3, LLM_GEMMA2, LLM_GEMMA3, LLM_GEMINI]

ENVIRONMENT_DIR = os.path.join(ROOT_DIR, ".venv")
SLURM_CONFIG_DIR = os.path.join(ROOT_DIR, "slurm-config/")
LOCAL_LLM = True
LLM_SERVER_BACKEND = os.getenv("LLMGE_SERVER_BACKEND", "vllm")
HOSTNAME_DIR = os.path.join(ROOT_DIR, "hostname.log")

# Multi-island settings
GLOBAL_DATA_PATH = "global_data"
PROMPT_GROUP_TEMPLATE = "templates/{prompt_group}/**/*.txt"
MAX_ISLANDS = len(ISLAND_LLMS)

SLURM_MIXT_INPUT_X = SEED_NETWORK
SLURM_MIXT_INPUT_Y = os.path.join(SOTA_ROOT, "models/Menghao/model_x.py")
SLURM_MIXT_OUTPUT = os.path.join(SOTA_ROOT, "models/Menghao/model_z.py")
SLURM_MIXT_TOP_P = 0.15
SLURM_MIXT_TEMPERATURE = 0.1
SLURM_MIXT_APPLY_QUALITY_CONTROL = True
SLURM_MIXT_BIT = 8

ISLAND_CONTROLLER_RUN_NAME = "titanic_islands_run2"
ISLAND_CONTROLLER_NUM_ISLANDS = 2
ISLAND_CONTROLLER_LLMS = "llama3"
ISLAND_CONTROLLER_PROMPT_GROUPS = "titanic/focused,titanic/general,titanic/roleplay"

# Load SLURM templates from slurm_config.yaml (generated by slurm.py)
_slurm_config_path = os.path.join(SLURM_CONFIG_DIR, 'slurm_config.yaml')
if os.path.exists(_slurm_config_path):
    with open(_slurm_config_path, 'r') as _f:
        _slurm_config = yaml.safe_load(_f)
    LLM_GPU = _slurm_config.get('gpu_selection', 'H200|H100')
    PYTHON_BASH_SCRIPT_TEMPLATE = _slurm_config.get('python_bash_script', '')
    LLM_BASH_SCRIPT_TEMPLATE = _slurm_config.get('llm_bash_script', '')
    ISLANDS_BASH_SCRIPT_TEMPLATE = _slurm_config.get('islands_bash_script', '')
else:
    # Fallback defaults if slurm_config.yaml hasn't been generated yet
    LLM_GPU = 'H200|H100'
    PYTHON_BASH_SCRIPT_TEMPLATE = ''
    LLM_BASH_SCRIPT_TEMPLATE = ''
    ISLANDS_BASH_SCRIPT_TEMPLATE = ''

INFERENCE_SUBMISSION = False

LOCAL = os.getenv("LOCAL", "false").lower() in ("true", "1", "yes")
if LOCAL:
    RUN_COMMAND = 'bash'
    DELAYED_CHECK = os.getenv("DELAYED_CHECK", "false").lower() in ("true", "1", "yes")
else: 
    RUN_COMMAND = 'sbatch'
    DELAYED_CHECK = os.getenv("DELAYED_CHECK", "true").lower() in ("true", "1", "yes")
MACOS = platform.system() == "Darwin"
RUNLINE_AMP = ''
# Keep constants import side-effect free. In particular, do not call
# torch.cuda.is_available() here: server_vllm imports this module before vLLM
# forks worker processes, and touching CUDA in the parent process can make
# Slurm/exclusive-process GPUs look busy to the workers.
if MACOS:
    DEVICE = os.getenv("LLMGE_DEVICE", "mps")
    RUNLINE_AMP = "-amp" if DEVICE == "mps" else ""
else:
    DEVICE = os.getenv("LLMGE_DEVICE", "cuda")

# resolves to {MODEL}_{gene_id}
RUNLINE_TMP = '{}_{}'
EVAL_RUNLINE = "uv run python {} --model {} --variant_dir {VARIANT_DIR}"
# Kill evaluation jobs that do not produce a terminal result in this window.
EVAL_NO_PROGRESS_TIMEOUT_SECONDS = int(os.getenv("LLMGE_EVAL_NO_PROGRESS_TIMEOUT_SECONDS", str(40 * 60)))

# Configuration validation: Check for vLLM-specific configs when USE_VLLM is False
if not USE_VLLM:
    _vllm_specific_vars = {
        "TENSOR_PARALLEL_SIZE": os.getenv("TENSOR_PARALLEL_SIZE"),
        "GPU_MEMORY_UTILIZATION": os.getenv("GPU_MEMORY_UTILIZATION"),
        "MAX_MODEL_LEN": os.getenv("MAX_MODEL_LEN"),
        "VLLM_DTYPE": os.getenv("VLLM_DTYPE"),
        "VLLM_QUANTIZATION": os.getenv("VLLM_QUANTIZATION"),
        "ENABLE_PREFIX_CACHING": os.getenv("ENABLE_PREFIX_CACHING"),
        "VLLM_DISABLE_CUSTOM_ALL_REDUCE": os.getenv("VLLM_DISABLE_CUSTOM_ALL_REDUCE"),
        "VLLM_WORKER_MULTIPROC_METHOD": os.getenv("VLLM_WORKER_MULTIPROC_METHOD"),
        "VLLM_USE_FLASHINFER_SAMPLER": os.getenv("VLLM_USE_FLASHINFER_SAMPLER"),
        "VLLM_ATTENTION_BACKEND": os.getenv("VLLM_ATTENTION_BACKEND"),
    }

    _set_vllm_vars = {k: v for k, v in _vllm_specific_vars.items() if v is not None}

    if _set_vllm_vars:
        _error_msg = (
            "Configuration Error: vLLM-specific environment variables are set, but USE_VLLM=False.\n"
            f"The following vLLM-specific variables are configured:\n"
        )
        for var, val in _set_vllm_vars.items():
            _error_msg += f"  - {var}={val}\n"
        _error_msg += (
            "\nTo fix this issue, either:\n"
            "  1. Set LLMGE_USE_VLLM=1 to enable vLLM, or\n"
            "  2. Unset the vLLM-specific environment variables\n"
        )
        raise ValueError(_error_msg)

"""
Evolution Constants/Params
"""
FITNESS_WEIGHTS = (-1.0, -1.0)
INVALID_FITNESS_MAX = tuple([float(x*np.inf*-1) for x in FITNESS_WEIGHTS])
PLACEHOLDER_FITNESS = tuple([int(x*9999999999*-1) for x in FITNESS_WEIGHTS])
NUM_EOT_ELITES = 10
GENERATION = 0
PROB_QC = 0.0
PROB_EOT = 0.25
num_generations = 5 # Number of generations
start_population_size = 32  # Starting population size
# start_population_size = 144   # Size of the population 124=72
#population_size = 44 # with cx_prob (0.25) and mute_prob (0.7) you get about %50 successful turnover
population_size = 32 # with cx_prob (0.25) and mute_prob (0.7) you get about %50 successful turnover
crossover_probability = 0.35  # Probability of mating two individuals
mutation_probability = 0.8 # Probability of mutating an individual
num_elites = 8
hof_size = 100
max_gen_attempts = 5
migration_gen = 5
"""
Misc. Non-sense
"""
DNA_TXT = """
⠀⠀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣶⣶⠶⣶⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⣀⣹⣟⣛⣛⣻⣿⣿⣿⡾⠟⢉⣴⠟⢁⣴⠋⣹⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠈⠛⠛⣿⠉⢉⣩⠵⠚⠁⢀⡴⠛⠁⣠⠞⠁⣰⠏⠸⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⢻⣷⠋⠁⠀⢀⡴⠋⠀⢀⡴⠋⠀⣼⠃⠀⡼⢿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢻⣆⣠⡴⠋⠀⠀⣠⠟⠀⢀⡾⠁⠀⡼⠁⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠻⣯⡀⠀⢀⡼⠃⠀⢠⡟⠀⢀⡾⠁⢀⣾⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠙⠻⣶⣟⡀⠀⣰⠏⠀⢀⡾⠁⠀⣼⢹⣿⣀⣤⣤⣴⠶⢿⡿⠛⢛⣷⢶⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⠿⠶⠶⠾⠷⠶⠿⠛⢻⣟⠉⣥⠟⠁⣠⠟⠀⢠⠞⠁⣄⡿⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⠞⠁⢀⡴⠋⠀⣴⠋⠀⣰⠟⠀⣤⡾⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡄⢠⠞⠁⢀⡾⠁⢀⡼⠃⢀⡴⠋⠀⢸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣷⠋⠀⣰⠏⠀⣠⠟⠀⣰⠟⠁⢀⡴⠛⣿⠀⠀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣧⡼⠃⢀⡼⠋⢠⡞⠁⣠⣞⣋⣤⣶⣿⡟⠛⣿⠛⠛⣻⠟⠷⢶⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⣦⣾⣤⣴⣯⡶⠾⠟⠛⠉⠉⠉⣿⡇⢠⡏⠀⣰⠏⠀⢀⣼⠋⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⡾⠀⢰⠏⠀⢠⡞⠁⠀⣠⠞⢻⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣷⠇⢠⠏⠀⣰⠋⠀⣠⠞⠁⠀⢀⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡟⢠⠟⢀⡼⠁⣠⠞⠁⣀⣴⢾⣿⣤⣿⣦⣄⣀⡀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⡟⣠⠏⣠⠞⣁⣴⣾⣿⣿⣿⣿⣿⣿⡏⢹⡏⠛⠳⣦⣄⡀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⢷⣾⣷⠿⠿⠛⠉⠀⠀⠈⠳⣬⣿⡟⣾⠁⠀⣼⠃⠉⠻⠆
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣧⡏⠀⣼⠃⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠁⡼⠁⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣟⡼⠁⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡿⠁⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢙⣃⠀⠀
"""
