shopt -s globstar
rm -rf run_job_outputs/**/slurm-*.out
rm -rf sota/**/**/models/llmge_models/*
rm -rf titanic_test/0
rm -rf sota/ExquisiteNetV2/models/*
rm -rf sota/ExquisiteNetV2/weight/*
rm -rf sota/Point-Transformers/models/llmge_models/*
rm -rf slurm-config/slurm_config.json
rm -rf sota/Point-Transformers/results/*
rm -rf sota/ExquisiteNetV2/results/*
