#!/bin/bash
# Use this file to move all files generated by LLMGE to a destination directory of your choice $DEST_DIR$
# Edit the paths for

# Define the destination directory
DEST_DIR="your_naming_choice"

# Create the destination directory if it doesn't exist
mkdir -p "$DEST_DIR"

# Move the output files from the Guided Evolution to $DEST_DIR$
mv -f slurm-*.out "$DEST_DIR/"                                                          # Slurm output files
mv -f 0 "$DEST_DIR/"                                                                    # LLM operation and gene evaluation bash scripts
mv -f sota/ultralytics/ultralytics/cfg/models/llm/models/* "$DEST_DIR/"                 # LLM generated models
mv -f sota/ultralytics/results/* "$DEST_DIR/"                                           # Model results from evaluation
mv -f sota/ultralytics/run_results/* "$DEST_DIR/"                                           # Model results from evaluation

# Run these if you need to move everything, otherwise, comment them out
# Note: mv -f is used to overwrite existing files in the destination without prompt
mv -f first_test/* "$DEST_DIR/"                                                         # Checkpoint pkl files
mv -f templates/FixedPrompts/roleplay/mutant*.txt "$DEST_DIR/"                          # mutated prompt files
mv -f templates/FixedPrompts/concise/mutant*.txt "$DEST_DIR/"                           # more mutated prompt files
mv -f runs/detect/* "$DEST_DIR/"                                                        # 