[project]
name = "surrogate-evaluation"
version = "0.1.0"
description = "evaluation for the surrogate evolution problem."
readme = "README.md"
requires-python = ">=3.9,<3.12"
dependencies = [
    "accelerate",
    "bitsandbytes",
    "ConfigSpace==0.4.21",
    "deap==1.4.3",
    "emcee",
    "fastapi",
    "flake8>=7.2.0",
    "fvcore",
    "furo>=2024.8.6",
    "gdown",
    "google-genai>=1.12.1",
    "grakel",
    "hydra-core==1.3.2",
    "imblearn",
    "kaggle>=1.6.0",
    "lightgbm",
    "matplotlib",
    "nasbench301",
    "nasbench-pytorch",
    "ngboost",
    "numpy<2.0",
    "omegaconf",
    "pandas",
    "pybnn",
    "pydantic",
    "pyro-ppl",
    "pytest>=8.3.5",
    "pytorch-msssim",
    "pyyaml",
    "requests",
    "scikit-image",
    "scikit-learn>=1.3.0",
    "scipy",
    "seaborn",
    "sphinx>=7.0.0",
    "tensorwatch",
    "tensorflow>=2.15.0,<2.18.0",
    "torch",
    "torchaudio",
    "torchvision",
    "tornado",
    "tqdm",
    "transformers",
    "transforms3d",
    "uvicorn",
    "xgboost",
]

[tool.uv.sources]
nasbench-pytorch = { git = "https://github.com/romulus0914/NASBench-PyTorch", rev = "master" }
nasbench301 = { git = "https://github.com/automl/nasbench301", rev = "no_gin" }