"""API types for the RAG component boundary.

All dataclasses are frozen (immutable after construction) and JSON-serializable
via :func:`dataclasses.asdict`.  No heavy ML dependencies (torch, faiss,
sentence-transformers) are imported here — this module must be importable in
any environment.

Cross-reference: docs/plans/05_rag_componentization_plan.md lines 82-157.
"""

from __future__ import annotations

import dataclasses
from typing import Any, Dict, List, Optional, Union


@dataclasses.dataclass(frozen=True)
class RetrieveRequest:
    """Request to retrieve relevant blocks from a RAG backend.

    Attributes:
        query: Natural-language or code query string.
        namespace: Logical corpus namespace (e.g. ``"pytorch_api"``,
            ``"mutation_history"``).  ``None`` means search all namespaces.
        top_k: Maximum number of blocks to return.
        filters: Arbitrary JSON-safe dict of source-type or metadata filters,
            e.g. ``{"source_types": ["api", "pdf"]}``.
        run_id: Optional run identifier for provenance / bookkeeping.
        request_id: Caller-supplied idempotency key; auto-generated by the
            caller if not provided.
    """

    query: str
    namespace: Optional[str] = None
    top_k: int = 5
    filters: Optional[Dict[str, Any]] = None
    run_id: Optional[str] = None
    request_id: Optional[str] = None


@dataclasses.dataclass(frozen=True)
class RetrievedBlock:
    """A single retrieved context block returned by the backend.

    Attributes:
        kind: Source kind tag, e.g. ``"api_doc"``, ``"pdf_chunk"``,
            ``"mutation_code"``.
        document_id: Stable unique identifier for the source document/chunk.
        title: Human-readable title or section heading.
        score: Similarity or reranker score (higher is more relevant).
        content: Raw text content of the block.
        diagnostics: Arbitrary JSON-safe dict of per-block diagnostics, e.g.
            ``{"candidate_count": 24, "reranked": True, "source": "faiss"}``.
    """

    kind: str
    document_id: str
    title: str
    score: float
    content: str
    diagnostics: Optional[Dict[str, Any]] = None


@dataclasses.dataclass(frozen=True)
class RetrieveResponse:
    """Response from a retrieve call.

    Attributes:
        blocks: Ordered list of retrieved blocks (most relevant first).
        diagnostics: Arbitrary JSON-safe dict of request-level diagnostics,
            e.g. ``{"reranker_used": True}``.
        latency_ms: Wall-clock time for the full retrieve call in milliseconds.
    """

    blocks: List[RetrievedBlock]
    diagnostics: Optional[Dict[str, Any]] = None
    latency_ms: float = 0.0


@dataclasses.dataclass(frozen=True)
class AugmentRequest:
    """Request to augment a mutation prompt using retrieved context.

    Attributes:
        template: Raw prompt template string (before RAG augmentation).
        mutation_type: LLMGE mutation type label, e.g. ``"Complex"``,
            ``"Param"``.
        query_code: Source code snippet used as the retrieval query.
        gene_id: Optional gene identifier for bookkeeping.
        run_id: Optional run identifier for bookkeeping.
        request_id: Caller-supplied idempotency key.
    """

    template: str
    mutation_type: str
    query_code: str
    gene_id: Optional[str] = None
    run_id: Optional[str] = None
    request_id: Optional[str] = None


@dataclasses.dataclass(frozen=True)
class AugmentResponse:
    """Response from an augment call.

    Attributes:
        augmented_prompt: The final prompt text after RAG augmentation.
        blocks_used: The retrieved blocks that were injected into the prompt.
        diagnostics: Arbitrary JSON-safe dict of call-level diagnostics.
        latency_ms: Wall-clock time for the full augment call in milliseconds.
    """

    augmented_prompt: str
    blocks_used: List[RetrievedBlock]
    diagnostics: Optional[Dict[str, Any]] = None
    latency_ms: float = 0.0


# Union type aliases — mirrors the plan's ``RagRequest`` / ``RagResponse``
# notation (docs/plans/05_rag_componentization_plan.md).
RagRequest = Union[AugmentRequest, RetrieveRequest]
RagResponse = Union[AugmentResponse, RetrieveResponse]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def retrieve_response_from_dict(d: Dict[str, Any]) -> RetrieveResponse:
    """Reconstruct a :class:`RetrieveResponse` from a plain dict (e.g. after
    JSON round-trip via :func:`dataclasses.asdict` + ``json.loads``).
    """
    blocks = [RetrievedBlock(**b) for b in d.get("blocks", [])]
    return RetrieveResponse(
        blocks=blocks,
        diagnostics=d.get("diagnostics"),
        latency_ms=d.get("latency_ms", 0.0),
    )


def augment_response_from_dict(d: Dict[str, Any]) -> AugmentResponse:
    """Reconstruct an :class:`AugmentResponse` from a plain dict."""
    blocks = [RetrievedBlock(**b) for b in d.get("blocks_used", [])]
    return AugmentResponse(
        augmented_prompt=d["augmented_prompt"],
        blocks_used=blocks,
        diagnostics=d.get("diagnostics"),
        latency_ms=d.get("latency_ms", 0.0),
    )
