name: GitHub Pages

on:
  push:
    branches:
      - new_main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build docs
        run: scripts/workflows/sphinx_deploy.sh
        shell: bash

      - name: Downloadable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloadable-site-build
          path: docs/build/html/ # The directory where the built files live


      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'jasonzutty/llm-guided-evolution-fork'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
